### ISSUE TITLE
Not handling HTTP 429 responses

### ISSUE THREAD

**Issue by chrisbanes** [ChrisKruegerDev/trakt-kotlin#43]
I got the following exception logged in Crashlytics:

```
Exception: Uj: Client request(POST https://api.trakt.tv/sync/history) invalid: 429 . Text: "AUTHED_API_POST_LIMIT rate limit exceeded. Please wait 1 seconds then retry your request."
       at io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:54)
       at io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt:13)
       at io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt:13)
       at io.ktor.client.plugins.HttpCallValidator.validateResponse(HttpCallValidator.kt:51)
       at io.ktor.client.plugins.HttpCallValidator.access$validateResponse(HttpCallValidator.kt:43)
       at io.ktor.client.plugins.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:152)
```

We should add retry backoff.

**Comment by ChrisKruegerDev** [comment]
Yep, definitively. Something I had in mind when I started with the lib. I will have a look after I am back in the office!

https://github.com/MoviebaseApp/trakt-kotlin/blob/main/lib/src/commonMain/kotlin/app/moviebase/trakt/core/HttpClientFactory.kt#L82
